### PR TITLE
Instalment changes due to payment history (issue #38)

### PR DESCRIPTION
**Pull request by dariodinizg**
##### What this PR made?
Related to issue #38 
Updates:
- Instalments now vary due to made or missed payments
- New database column to keep instalments value inside Payment model
- New response.data for payments payload: {"payment": "made", "received": "85.69", "expected": "93.48"}
- RAML updated to embrace the new response.data for payment post.
- FIXED: There were missing lines in the code after the merge. Some tests without assert statement.

##### Where could the review begin?
calculator/models.py
calculator/test/test_models.py
calculator/test/test_payment_view.py

##### How this could be tested manually?
$ python manage.py test -v2

### CODE REVIEW

**Review by cesarbruschetta — COMMENTED** [review]
@dariodinizg 
good modifications, I just wanted to point out that `coveralls` is accusing error, since the project coverage rate dropped from **42%** to **41%**, I do not know if this is a big problem now for us to attack, because it can be just something is failing to set up in the `coverage` tool but only wanted to punctuate the alert...

### Ref
https://coveralls.io/builds/23472056

**Comment by julianeventeu** [comment]
> @dariodinizg
> good modifications, I just wanted to point out that `coveralls` is accusing error, since the project coverage rate dropped from **42%** to **41%**, I do not know if this is a big problem now for us to attack, because it can be just something is failing to set up in the `coverage` tool but only wanted to punctuate the alert...
> 
> ### Ref
> https://coveralls.io/builds/23472056

I checked the previous report and the current report, I think the problems is on /home, because the path /api_fintech and /calculator the coverage percentual is the same.
I will search for how to remove this path from coverage.

**Review by julianeventeu — APPROVED** [review]

**Comment by dariodinizg** [comment]
> @dariodinizg
> good modifications, I just wanted to point out that `coveralls` is accusing error, since the project coverage rate dropped from **42%** to **41%**, I do not know if this is a big problem now for us to attack, because it can be just something is failing to set up in the `coverage` tool but only wanted to punctuate the alert...
> ### Ref
> 
> https://coveralls.io/builds/23472056

Travis pointed an error and, i think, its related to the date validation we implemented, cause is the only test with a payment within april (not current month). If he is checking validation for our tests and our date was inserted as strings, I think we will have problem with our tests in june, cause all our other dates is pointed to may.

You may check here: https://travis-ci.org/cesarbruschetta/api-fintech/builds/534317960?utm_source=github_status&utm_medium=notification
@cesarbruschetta @julianeventeu

**Comment by julianeventeu** [comment]
> > @dariodinizg
> > good modifications, I just wanted to point out that `coveralls` is accusing error, since the project coverage rate dropped from **42%** to **41%**, I do not know if this is a big problem now for us to attack, because it can be just something is failing to set up in the `coverage` tool but only wanted to punctuate the alert...
> > ### Ref
> > https://coveralls.io/builds/23472056
> 
> Travis pointed an error and, i think, its related to the date validation we implemented, cause is the only test with a payment within april (not current month). If he is checking validation for our tests and our date was inserted as strings, I think we will have problem with our tests in june, cause all our other dates is pointed to may.
> @cesarbruschetta @julianeventeu

Yes, it will be a problem, but it is easy to fix.
When I wrote the validation about the current month I changed some tests to use the today date, because this way the test always be pass, independent from month.
I think we can change all tests about payment valid to use this date like this:

**date = datetime.strftime(datetime.today().astimezone(tz=timezone.utc), "%Y-%m-%d %H:%M%z")
valid_payloan = {"payment": "made", "amount": 1000, "date": date}**

**Comment by dariodinizg** [comment]
Will this break the test code that uses multiple payments, with.multiple dates?

**Review by cesarbruschetta — APPROVED** [review]

**Pull request merged**
